stages:
  data_ingestion:
    cmd: python src/data/data_injection.py
    deps:
    - src/data/data_injection.py
    - src/custom_logging/__init__.py
    - src/exeption/__init__.py
    - src/utils/__init__.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - src/data/data_preprocessing.py
    - src/custom_logging/__init__.py
    - src/exeption/__init__.py
    - src/utils/__init__.py
    - data/raw
    outs:
    - data/interim
  feature engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - src/features/feature_engineering.py
    - src/custom_logging/__init__.py
    - src/exeption/__init__.py
    - src/utils/__init__.py
    - data/interim
    outs:
    - data/processed
    - models/objects
  model training:
    cmd: python src/models/train_model.py
    deps:
    - src/models/train_model.py
    - src/custom_logging/__init__.py
    - src/exeption/__init__.py
    - src/utils/__init__.py
    - data/processed
    outs:
    - models/model
  model Evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - src/models/model_evaluation.py
    - src/custom_logging/__init__.py
    - src/exeption/__init__.py
    - src/utils/__init__.py
    - models/model
   
 

